# Generated by Django 2.2.4 on 2019-09-04 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='russia1',
            new_name='Bottom',
        ),
    ]
