# Generated by Django 2.2.4 on 2019-09-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0002_auto_20190904_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottom',
            name='img1',
            field=models.ImageField(upload_to='Services'),
        ),
    ]
