# Generated by Django 2.2.4 on 2019-09-04 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0003_auto_20190905_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottom',
            old_name='alter1',
            new_name='alter',
        ),
        migrations.RenameField(
            model_name='bottom',
            old_name='desc1',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='bottom',
            old_name='img1',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='bottom',
            old_name='name1',
            new_name='name',
        ),
    ]
