# Generated by Django 2.2.4 on 2019-09-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0004_auto_20190905_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dost_name', models.CharField(max_length=100)),
                ('dost_image', models.ImageField(upload_to='Services')),
                ('dost_alter', models.CharField(max_length=50)),
                ('dost_desc', models.TextField()),
                ('dost_link', models.URLField()),
            ],
        ),
    ]
