# Generated by Django 2.2.4 on 2019-09-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0006_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100)),
                ('offer_image', models.ImageField(upload_to='Services')),
                ('offer_alter', models.CharField(max_length=50)),
                ('offer_desc', models.TextField()),
                ('offer_link', models.URLField()),
            ],
        ),
    ]
