# Generated by Django 2.2.4 on 2019-09-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0008_bottom_lin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Last',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('last_image', models.ImageField(upload_to='Services')),
                ('dost_alter', models.CharField(max_length=50)),
                ('dost_desc', models.TextField()),
                ('dost_link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='offers',
            name='offer_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
