# Generated by Django 2.2.4 on 2019-09-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0009_auto_20190909_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='last',
            old_name='dost_alter',
            new_name='last_alter',
        ),
        migrations.RemoveField(
            model_name='last',
            name='dost_desc',
        ),
        migrations.RemoveField(
            model_name='last',
            name='dost_link',
        ),
        migrations.AddField(
            model_name='last',
            name='last_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='last',
            name='last_file',
            field=models.FileField(blank=True, null=True, upload_to='Services'),
        ),
        migrations.AddField(
            model_name='last',
            name='last_link1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='last',
            name='last_link2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='last',
            name='last_reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='last',
            name='last_image',
            field=models.ImageField(blank=True, null=True, upload_to='Services'),
        ),
    ]
