# Generated by Django 2.2.4 on 2019-10-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0012_auto_20190909_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('city_image', models.ImageField(upload_to='Services')),
                ('city_alter', models.CharField(max_length=50)),
                ('city_desc', models.TextField()),
                ('city_link', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Famous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fame_name', models.CharField(max_length=100)),
                ('fame_image', models.ImageField(upload_to='Services')),
                ('fame_alter', models.CharField(max_length=50)),
                ('fame_desc', models.TextField()),
                ('fame_link', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
